export const notifications: TNotificationProps[] = [
  {
    user: "Ishema Hugues",
    message: "Got a problem in Musanze",
    status: "got-issues",
    sentAt: "5m",
  },
  {
    user: "Ishema Hugues",
    message: "Stopped for gas",
    status: "stopped",
    sentAt: "1hr",
  },
  {
    user: "Ishema Hugues",
    message: "Started journey NYABUGOGO - MUSANZE",
    status: "started",
    sentAt: "2hr",
  },
  {
    user: "Ishema Hugues",
    message: "Arrived in Nyabugogo",
    status: "arrived",
    sentAt: "1m",
  },
  {
    user: "Ishema Hugues",
    message: "Got a problem in Musanze",
    status: "got-issues",
    sentAt: "5m",
  },
  {
    user: "Ishema Hugues",
    message: "Stopped for gas",
    status: "stopped",
    sentAt: "1hr",
  },
  {
    user: "Ishema Hugues",
    message: "Started journey NYABUGOGO - MUSANZE",
    status: "started",
    sentAt: "2hr",
  },
  {
    user: "Ishema Hugues",
    message: "Arrived in Nyabugogo",
    status: "arrived",
    sentAt: "1m",
  },
];

export const teamMembers: TeamMember[] = [
  {
    name: "John Smith",
    id: "001",
    role: "Manager",
    imgUrl: "https://picsum.photos/200/300/?1",
  },
  {
    name: "Alice Johnson",
    id: "002",
    role: "Driver",
    imgUrl: "https://picsum.photos/200/300/?2",
  },
  {
    name: "David Brown",
    id: "003",
    role: "Dispatcher",
    imgUrl: "https://picsum.photos/200/300/?3",
  },
  {
    name: "Sarah Davis",
    id: "004",
    role: "Mechanic",
    imgUrl: "https://picsum.photos/200/300/?4",
  },
  {
    name: "Emily Wilson",
    id: "005",
    role: "Technician",
    imgUrl: "https://picsum.photos/200/300/?5",
  },
  {
    name: "John Smith",
    id: "001",
    role: "Manager",
    imgUrl: "https://picsum.photos/200/300/?1",
  },
  {
    name: "Alice Johnson",
    id: "002",
    role: "Driver",
    imgUrl: "https://picsum.photos/200/300/?2",
  },
];

export const teamMembersTableData: TeamMemberData[] = [
  {
    name: "John Smith",
    id: "001",
    imgUrl: "https://picsum.photos/200/300/?1",
    email: "john@example.com",
    status: "active online",
    phoneNumber: "123-456-7890",
    createdAt: "12/2/2023",
  },
  {
    name: "Alice Johnson",
    id: "002",
    imgUrl: "https://picsum.photos/200/300/?2",
    email: "alice@example.com",
    status: "active offline",
    phoneNumber: "234-567-8901",
    createdAt: "12/2/2023",
  },
  {
    name: "David Brown",
    id: "003",
    imgUrl: "https://picsum.photos/200/300/?3",
    email: "david@example.com",
    status: "deactivated",
    phoneNumber: "345-678-9012",
    createdAt: "12/2/2023",
  },
  {
    name: "Sarah Davis",
    id: "004",
    imgUrl: "https://picsum.photos/200/300/?4",
    email: "sarah@example.com",
    status: "blocked",
    phoneNumber: "456-789-0123",
    createdAt: "12/2/2023",
  },
  {
    name: "Emily Wilson",
    id: "005",
    imgUrl: "https://picsum.photos/200/300/?5",
    email: "emily@example.com",
    status: "active online",
    phoneNumber: "567-890-1234",
    createdAt: "12/2/2023",
  },
];

export const vehiclesTableData: VehicleInfo[] = [
  {
    name: "John Smith",
    id: "001",
    imgUrl: "https://picsum.photos/200/300/?1",
    email: "john@example.com",
    status: "active online",
    phoneNumber: "123-456-7890",
    createdAt: "12/2/2023",
    plateNumber: "RAE 234 J",
  },
  {
    name: "Alice Johnson",
    id: "002",
    imgUrl: "https://picsum.photos/200/300/?2",
    email: "alice@example.com",
    status: "active offline",
    phoneNumber: "234-567-8901",
    createdAt: "12/2/2023",
    plateNumber: "RAE 234 J",
  },
  {
    name: "David Brown",
    id: "003",
    imgUrl: "https://picsum.photos/200/300/?3",
    email: "david@example.com",
    status: "deactivated",
    phoneNumber: "345-678-9012",
    createdAt: "12/2/2023",
    plateNumber: "RAE 234 J",
  },
  {
    name: "Sarah Davis",
    id: "004",
    imgUrl: "https://picsum.photos/200/300/?4",
    email: "sarah@example.com",
    status: "blocked",
    phoneNumber: "456-789-0123",
    createdAt: "12/2/2023",
    plateNumber: "RAE 234 J",
  },
  {
    name: "Emily Wilson",
    id: "005",
    imgUrl: "https://picsum.photos/200/300/?5",
    email: "emily@example.com",
    status: "active online",
    phoneNumber: "567-890-1234",
    createdAt: "12/2/2023",
    plateNumber: "RAE 234 J",
  },
];

export const vehiclesData: Vehicle[] = [
  {
    source: "kigali",
    destination: "Musanze",
    currentLocation: "Rulindo",
    plateNumber: "RAE 234 J",
    type: "Bus",
    id: "001",
  },
  {
    source: "kigali",
    destination: "Musanze",
    currentLocation: "Rulindo",
    plateNumber: "RAE 234 J",
    type: "Bus",
    id: "002",
  },
  {
    source: "kigali",
    destination: "Musanze",
    currentLocation: "Rulindo",
    plateNumber: "RAE 234 J",
    type: "Bus",
    id: "003",
  },
  {
    source: "kigali",
    destination: "Musanze",
    currentLocation: "Rulindo",
    plateNumber: "RAE 234 J",
    type: "Bus",
    id: "004",
  },
];


export const navigatingRoutes: TRoute[] = [
  {
    location: "Rubavu to Hotel de mille collines",
    address: "Some bus stop address in Rubavu",
    latitude: -1.722222,
    longitude: 29.629444,
    id: "778580a1-adaa-4cc5-9440-7bbe6ff4b48c",
  },
  {
    location: "Musanze to Kigali",
    address: "Some bus stop address in Musanze",
    latitude: -1.496111,
    longitude: 29.663611,
    id: "ca4d0b87-23cc-4d67-9172-82e6c98c433c",
  },
  {
    location: "Kigali to Rwanda Coding Academy",
    address: "Some bus stop address near Rwanda Coding Academy",
    latitude: -1.944444,
    longitude: 29.861111,
    id: "7bbf2a26-46cd-4d41-a4a1-5c12421c5b2a",
  },
  {
    location: "Nyagatare to Kigali",
    address: "Some bus stop address in Nyagatare",
    latitude: -2.033333,
    longitude: 30.291667,
    id: "745c5651-1008-49b6-8f1e-2db413b905a9",
  },
  {
    location: "Muhanga to Kigali",
    address: "Some bus stop address in Muhanga",
    latitude: -2.066667,
    longitude: 29.983333,
    id: "5111aeb1-3ded-445a-ac82-1cd75693892d",
  },
];